//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_65133295.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIETHOADONs = new HashSet<CHITIETHOADON>();
        }
    
        public string maHD { get; set; }
        public string maDH { get; set; }
        public System.DateTime ngayThanhToan { get; set; }
        public string maNV { get; set; }
        public string maKM { get; set; }
        public decimal tongTienTamTinh { get; set; }
        public Nullable<decimal> soTienGiamKM { get; set; }
        public decimal tongTienPhaiTra { get; set; }
        public string phuongThucThanhToan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHOADON> CHITIETHOADONs { get; set; }
        public virtual DONHANG DONHANG { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
